---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
    theme: "paper"
    navbar:
      - { title: "Home", href: index.html, align: left }
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Column {data-width=650}
-----------------------------------------------------------------------

```{r, include = FALSE}
data("ny_noaa")
ny_noaa = 
  ny_noaa %>% 
  mutate(
    tmin = as.integer(tmin),
    tmax = as.integer(tmax)
  )%>% 
  separate(date,
           into = c("year", "month", "day"),
           sep = "-",
           convert = FALSE,
           remove = FALSE) %>% 
  mutate(
    tmin = tmin / 10,
    tmax = tmax / 10,
    prcp = prcp / 10
  )
```

### Chart A

```{r boxplot}
ny_noaa %>% 
  filter(id == "USC00300055") %>% 
  group_by(year, month) %>% 
  summarise(
    avg_prcp = mean(prcp)
  ) %>% 
  mutate(text_label = str_c("Month:", month)) %>% 
  plot_ly(
    x = ~year, y = ~avg_prcp, color = ~year,
    type = "box", colors = "viridis",
    text = ~text_label
  ) %>% 
  layout(title = 'Average Precipitation Monitered by USC00300055',
         xaxis = list(title = 'Year'),
         yaxis = list(title = 'Average Precipitation(mm)'))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r scatterplot}
ny_noaa %>% 
  drop_na(snow) %>% 
  group_by(year, month) %>% 
  summarise(
    avg_snow = mean(snow)
  ) %>% 
  mutate(text_label = str_c("Month:", month)) %>% 
  plot_ly(
    x = ~year, y = ~avg_snow, color = ~month,
    type = "scatter", mode = "markers", colors = "viridis",
    text = ~text_label
  ) %>% 
  layout(title = 'Monthly Average Snow Fall',
         xaxis = list(title = 'Year'),
         yaxis = list(title = 'Snow Fall (mm)'))


```

### Chart C

```{r hexplot}
tmin_vs_tmax = 
  ny_noaa %>% 
  drop_na(tmax, tmin) %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex() +
  labs(
    title = "tmax vs. tmin",
    x = "tmin (°C)",
    y = "tmax (°C)"
  ) + 
  theme_minimal() + 
  theme(legend.position = "bottom")

ggplotly(tmin_vs_tmax)
```

